### PR TITLE
Issue 1

### PR DESCRIPTION
**Pull request by ceterisp**
This is linked to #1 . At the moment there is no significant change I could make. Unfortunately, I will need some time on this issue. You have done some good work on this program. I want to take the time to learn and understand how the code works, so I am creating a draft PR. This way you can see and review every commit I make to this branch, or you can review it all at the end as you see fit. Let me know if this works for you.

I wasn't able to test the code but I wanted to make sure if I need to have the game in order to test the code? If not, could you tell me how I can test the program?

Thank you for letting me work on this issue! Looking forward to continuing to work on this issue!

### CODE REVIEW

**Comment by bjorno43** [comment]
Sounds good to me! I'll keep an eye on it. Unfortunately I do believe that you'll need the game in order to fully test it. This program extracts package files from the game allowing modders to create mods for the game. I'm not sure whether Hello Games (the owners of No Man's Sky) would allow publication of the extracted files, so I probably can't do this. But even if I could, it would still be impossible to actually test final results without the game.

What you could try though is download No Man's Sky mods from Nexusmods and extract those with this program. This will, at the very least, allow you to see how it works.

**Comment by ceterisp** [comment]
Got it! I will take the time to look through and see how I can have the application interact with the nexusmods website. Rest assured I am still on this issue and do my best to refactor code to the way you like. 
Thanks again for letting me continue contributing to this issue!

**Comment by ceterisp** [comment]
Hey @bjorno43 , sorry for being MIA until the end. I labelled your work as the most challenging project I want to contribute to since contributing to Hacktoberfest is part of my coursework. Thank you for not rejecting my draft earlier :)
I looked at the error messages in ConfigForm.cs file and decided to create a lookup function using switch arm. I created a function that takes 1-3 arguments which will return a specific string. If you like the lookup function, I will continue refactoring the rest of the error messages throughout the codebase. Let me know!

Thank you for your paitence!

**Comment by ceterisp** [comment]
Hey @bjorno43 I just marked my PR as ready to review. Please let me know if this PR is okay. 
Also, if this is not being accepted to hacktoberfest don't worry about it. I just want to make sure that I made the right refactoring changes that you like for this project. I'm open to changes if you find something you don't like. :)

Thank you again for letting me work on this issue!

**Comment by bjorno43** [comment]
@abuZayed15 Hey. Sorry I haven't responded in a long time. Unfortunately my life didn't allow me to focus on this project for a long time. I did review your code and everything seems fine with me. I'm not yet fit enough to fully check it all, but I did merge it for now. Once I'm back up and running, I'll check it more extensively to be absolutely sure. If it turns out to be a real problem, I can always revert the merge. Thanks a lot for all your help and dedication! I truly appreciate it!

**Comment by ceterisp** [comment]
@bjorno43 no worries, I hope everything is well for you. If there is a problem during the merge or some of your tests aren't running let me know and I will be happy to dive back into the code and fix the issue!

**Pull request merged**
